/*
 * Publishes the trading desk (../../desk) into public/desk so the marketing
 * site can serve it at /desk/index.html.
 *
 * The desk keeps a single source of truth: ../../desk/index.html. This script
 * runs automatically before `yarn start` and `yarn build` (see package.json
 * prestart/prebuild), so the bundled copy never drifts. public/desk is
 * generated and git-ignored.
 */
const fs = require("fs");
const path = require("path");

const SRC_DIR = path.join(__dirname, "..", "..", "desk");
const OUT_DIR = path.join(__dirname, "..", "public", "desk");
// Only the static assets the page actually loads. Secrets (local-config.js) are
// deliberately never copied. edge-config.js holds only a public Worker URL, so
// it is safe to publish.
const FILES = ["index.html", "volmodel.js", "volmodel2.js", "volworker.js", "freesrc.js", "edge-config.js"];

// desk/index.html loads local-config.js unconditionally, because that is how a
// local checkout supplies keys and an API base. That file must never be
// published (it can hold keys in plain text), so the published copy used to
// 404 on every visit. Stand in for it with a no-op that reproduces exactly what
// the desk does when the file is absent: no keys, and auto-detected API base.
const STUB = `/* Generated by frontend/scripts/sync-desk.js. Never edit this file and never
   put keys in it: the real local-config.js is git-ignored and is not published. */
window.DESK_KEYS = null;
window.DESK_API_BASE = undefined;
`;

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const name of FILES) {
    const from = path.join(SRC_DIR, name);
    if (!fs.existsSync(from)) {
      console.error(`[sync-desk] source not found: ${from}`);
      process.exit(1);
    }
    fs.copyFileSync(from, path.join(OUT_DIR, name));
  }
  fs.writeFileSync(path.join(OUT_DIR, "local-config.js"), STUB);
  console.log(`[sync-desk] bundled desk -> ${path.relative(process.cwd(), OUT_DIR)} (${FILES.join(", ")} + local-config.js stub)`);
}

main();
